apiVersion: autoscaling.openshift.io/v1
kind: ClusterAutoscaler
metadata:
  name: default
spec:
  podPriorityThreshold: -10
  resourceLimits:
    cores:
      max: 64
      min: 4
    maxNodesTotal: 10
    memory:
      max: 128
      min: 16
  scaleDown:
    delayAfterAdd: 2m
    delayAfterDelete: 2m
    delayAfterFailure: 30s
    enabled: true
    unneededTime: 60s