apiVersion: sriovnetwork.openshift.io/v1
kind: SriovNetwork
metadata:
  name: intel-netdevice
  namespace: openshift-sriov-network-operator
spec:
  ipam: |
    {
      "type": "host-local",
      "subnet": "10.56.215.0/24",
      "rangeStart": "10.56.215.171",
      "rangeEnd": "10.56.215.181",
      "routes": [{
        "dst": "0.0.0.0/0"
      }],
      "gateway": "10.56.215.1"
    }
  vlan: 0
  spoofChk: "on"
  trust: "off"
  resourceName: intelnetdevice
  networkNamespace: z1
