apiVersion: v1
data:
  secure-forward.conf: |
    <store>
      @type forward
      transport tls
      tls_cert_path /data/forward_ca_cert # Set the path to the certificate file.
      tls_verify_hostname false           # Set false to ignore cert hostname.
      <server>
        host 192.168.1.2
        port 24224
      </server>
    </store>
