apiVersion: metering.openshift.io/v1alpha1
kind: Report
metadata:
  name: namespace-cpu-request-grace-period
spec:
  reportingStart: '2019-07-11T20:09:00Z'
  reportingEnd: '2019-07-11T23:09:00Z'
  query: "namespace-cpu-request"
  graceperiod: '1h'
