apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: "fluentdserver1"
  labels:
    provider: aosqe
    component: "fluentd"
    logging-infra: "fluentdserver1"
  namespace: openshift-logging
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      provider: aosqe
      component: "fluentd"
      logging-infra: "fluentdserver1"
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        logging-infra: "fluentdserver1"
        provider: aosqe
        component: "fluentd"
    spec:
      containers:
      - name: "fluentd"
        image: "docker.io/fluent/fluentd:latest"
        imagePullPolicy: "IfNotPresent"
        ports:
        - containerPort: 24224
          name: fluentd
        securityContext:
          privileged: true
          procMount: Default
      serviceAccount: fluentdserver
      serviceAccountName: fluentdserver
