apiVersion: v1
kind: Pod
metadata:
  generateName: vlan100-pod-
  annotations:
    k8s.v1.cni.cncf.io/networks: vlan100
spec:
  containers:
  - name: vlan100-pod
    image: docker.io/bmeng/centos-network
