apiVersion: v1
kind: Pod
metadata:
  generateName: host-device-pod-
  labels:
    name: host-device-pod
  annotations:
    k8s.v1.cni.cncf.io/networks: host-device
spec:
  containers:
  - name: host-device-pod
    image: docker.io/bmeng/centos-network
