apiVersion: v1
kind: Pod
metadata:
  generateName: macvlan-private-pod-
  labels:
    name: macvlan-private-pod
  annotations:
    k8s.v1.cni.cncf.io/networks: macvlan-private
spec:
  containers:
  - name: macvlan-private-pod
    image: docker.io/bmeng/centos-network
