apiVersion: v1
kind: Pod
metadata:
  generateName: two-vlan100-pod-
  annotations:
    k8s.v1.cni.cncf.io/networks: vlan100, vlan100
spec:
  containers:
  - name: two-vlan100-pod
    image: docker.io/bmeng/centos-network
