apiVersion: v1
kind: Pod
metadata:
  generateName: vlan-hostdevice-pod-
  annotations:
    k8s.v1.cni.cncf.io/networks: vlan100, host-device
spec:
  containers:
  - name: vlan-hostdevice-pod
    image: docker.io/bmeng/centos-network
