apiVersion: metering.openshift.io/v1alpha1
kind: Report
metadata:
  name: namespace-memory-usage-cron-5min
spec:
  query: "namespace-memory-usage"
  schedule:
    period: "cron"
    cron:
      expression: "*/5 * * * *"

