apiVersion: metering.openshift.io/v1alpha1
kind: Report
metadata:
  name: namespace-memory-usage-aggreate-from-cron
spec:
  query: "namespace-memory-usage"
  schedule:
    period: "hourly"
  inputs:
  - name: NamespaceMemoryUsageReportName
    value: namespace-memory-usage-cron-5min
  gracePeriod: 1h # delay running 1 hour so that the hourly report has time to run
