apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs1
  annotations:
    description: "The description of PV"
spec:
  capacity:
    storage: 1Gi
  accessModes:
     - ReadWriteOnce
  nfs:
    path: /chaotest
    server: 10.14.6.144
  claimRef:
    namespace: default
    name: nfsc
