# useful for bastion pod
# ssh -o ProxyCommand="oc --config=/tmp/v4.kubeconfig exec -i bastion-0 -- nc %h %p" core@master-0.cluster-name.qe.devcluster.openshift.com

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: bastion
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bastion
  template:
    metadata:
      labels:
        app: bastion
    spec:
      containers:
      - name: main
        image: aosqe/pod-for-ping
        resources:
          limits:
            memory: 340Mi
