kind: ConfigMap
apiVersion: v1
metadata:
  name: multus-cni-config
  labels:
    tier: node
    app: multus
data:
  cni-conf.json: |
    {
      "name": "multus-cni-network",
      "type": "multus",
      "logFile": "/var/log/multus.log",
      "logLevel": "debug",
      "confDir": "/etc/kubernetes/cni/net.d/",
      "binDir": "/var/lib/cni/bin/",
      # the 80-openshift.conf should be found under /etc/kubernetes/cni/net.d/ 
      "clusterNetwork": "openshift-sdn",
      # the macvlan.conf which defined the macvlan-bridge should be found under /etc/kubernetes/cni/net.d/
      "defaultNetworks": ["macvlan-bridge"],
      "kubeconfig": "/etc/kubernetes/cni/net.d/multus.d/multus.kubeconfig"
    }
