apiVersion: v1
kind: Pod
metadata:
  generateName: offload-pod-1
  annotations:
    v1.multus-cni.io/default-network: z1/offload
spec:
  containers:
  - name: offload-pod-1
    image: quay.io/openshifttest/hello-sdn@sha256:d5785550cf77b7932b090fcd1a2625472912fb3189d5973f177a5a2c347a1f95
    imagePullPolicy: Always
    resources:
      limits:
        openshift.io/mlxnics: "1"
      requests:
        openshift.io/mlxnics: "1"
