kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: console-operator
  namespace: openshift-console
rules:
  - verbs:
      - get
      - list
      - watch
      - create
      - update
      - delete
    apiGroups:
      - console.openshift.io
    resources:
      - consoles
  - verbs:
      - get
      - list
      - watch
      - create
      - update
      - delete
      - patch
    apiGroups:
      - ''
    resources:
      - services
      - events
      - configmaps
      - secrets
  - verbs:
      - get
      - list
      - watch
    apiGroups:
      - ''
    resources:
      - pods
  - verbs:
      - get
      - list
      - watch
    apiGroups:
      - apps
    resources:
      - replicasets
  - verbs:
      - get
      - list
      - watch
      - create
      - update
      - delete
    apiGroups:
      - route.openshift.io
    resources:
      - routes
