apiVersion: console.openshift.io/v1
kind: ConsoleLink
metadata:
 name: examplethree
spec:
 href: 'https://www.example.com'
 location: NamespaceDashboard
 text: Special link three
 namespaceDashboard:
   namespaceSelector:
     matchExpressions:
        - key: test
          operator: Exists
     matchLabels:
       newtest: two
